. $(pwd)/vars/oracle.env

echo "COLUMN HOST_NAME FOR A13
COLUMN INSTANCE_NAME FOR A13
COLUMN VERSION FOR A10
COLUMN PARALLEL FOR A8
select INST_ID,INSTANCE_NUMBER,INSTANCE_NAME,HOST_NAME,VERSION,to_char(STARTUP_TIME,'DD-MON-YYYY HH24:MI:SS') INICIADA, 
STATUS,PARALLEL,THREAD#,ARCHIVER,DATABASE_STATUS
FROM GV\$INSTANCE
ORDER BY THREAD#;" | sqlplus -s $USER/$PW>@$DB > /tmp/infodb.log
